def solve():
    """Sum of perimeters of almost-equilateral triangles (sides a, a, a+-1) with
    integer area and perimeter <= 10^9.

    Integer area requires 4a^2 - b^2 to be a perfect square k^2 (b = a + e,
    e = +-1). With u = 3a - e this rearranges to the Pell equation
    u^2 - 3k^2 = 4, whose solutions are generated by u' = 2u + 3k, k' = u + 2k.
    """
    limit = 1_000_000_000
    total = 0
    u, k = 4, 2                       # seed (degenerate); first step gives (14, 8)
    while True:
        u, k = 2 * u + 3 * k, u + 2 * k
        e = 1 if (u + 1) % 3 == 0 else -1
        a = (u + e) // 3
        b = a + e
        perimeter = 2 * a + b
        if perimeter > limit:
            break
        if a >= 2:                    # exclude the degenerate small case
            total += perimeter
    return total

if __name__ == "__main__":
    print(solve())  # 518408346
