"""Project Euler 861: Products of Bi-Unitary Divisors.

For n = prod p_i^(a_i), a divisor with exponents c_i is bi-unitary iff
no prime has c_i = a_i - c_i != 0, i.e. c_i ranges over {0..a_i} minus
the midpoint when a_i is even.  The allowed exponent sets are symmetric
under c -> a - c with no fixed point, so pairing d with n/d gives
P(n) = n^(b(n)/2), where b(n) = prod f(a_i) with f(a) = 2 ceil(a/2) is
the number of bi-unitary divisors.  Thus P(n) = n^k iff b(n) = 2k, and
the required sum counts n <= 10^12 with b(n) in {4, 6, ..., 20}.

Since every factor f(a) is an even number >= 2, at most four distinct
primes can occur, and the admissible exponent multisets form a short
explicit list (generated by a small search over f-products).  Each
multiset is counted by assigning exponents to strictly increasing
primes in a depth-first search: the final prime is closed in O(1) by a
prime-count lookup of N / cur (Lucy_Hedgehog's O(N^(3/4)) sieve
provides pi at every floor(N/i)), or by an integer e-th root for a
final exponent e >= 2, and the second-to-last level is vectorised over
the penultimate prime with numpy.  The implementation reproduces the
given Q_2(10^2) = 51 and Q_6(10^6) = 6189 and matches a brute-force
factorisation count for all n <= 10^5.
"""

from __future__ import annotations

from math import isqrt

import numpy as np


def lucy_pi(n: int) -> tuple[int, np.ndarray, np.ndarray]:
    """Return (v, smalls, larges): smalls[x] = pi(x) for x <= v = isqrt(n),
    larges[i] = pi(n // i) for 1 <= i <= v."""
    v = isqrt(n)
    smalls = np.arange(v + 1, dtype=np.int64) - 1
    larges = np.zeros(v + 1, dtype=np.int64)
    idx = np.arange(1, v + 1)
    larges[1:] = n // idx - 1
    for p in range(2, v + 1):
        if smalls[p] == smalls[p - 1]:
            continue
        pc = int(smalls[p - 1])
        imax = min(v, n // (p * p))
        i = np.arange(1, imax + 1)
        d = i * p
        big = d <= v
        vals = np.where(
            big,
            larges[np.minimum(d, v)],
            smalls[np.minimum(n // np.maximum(d, 1), v)],
        )
        larges[1 : imax + 1] -= vals - pc
        if p * p <= v:
            prev = smalls.copy()
            smalls[p * p :] -= prev[np.arange(p * p, v + 1) // p] - pc
    return v, smalls, larges


def iroot(x: int, e: int) -> int:
    if e == 1:
        return x
    r = int(round(x ** (1.0 / e)))
    while r > 0 and r**e > x:
        r -= 1
    while (r + 1) ** e <= x:
        r += 1
    return r


def admissible_patterns(targets: set[int]) -> list[tuple[int, ...]]:
    """Exponent multisets whose bi-unitary divisor count lies in targets."""
    patterns: set[tuple[int, ...]] = set()
    top = max(targets)

    def gen(min_a: int, mult: list[int], fprod: int) -> None:
        if fprod in targets and mult:
            patterns.add(tuple(mult))
        for a in range(min_a, 21):
            f = 2 * ((a + 1) // 2)
            if fprod * f > top:
                if f > top:
                    break
                continue
            gen(a, [*mult, a], fprod * f)

    gen(1, [], 1)
    return sorted(patterns)


def count_with_b_in(n: int, ks: range) -> int:
    """Count 1 < m <= n whose bi-unitary divisor count equals 2k, k in ks."""
    targets = {2 * k for k in ks}
    v, smalls, larges = lucy_pi(n)
    sieve = np.ones(v + 1, dtype=bool)
    sieve[:2] = False
    for i in range(2, isqrt(v) + 1):
        if sieve[i]:
            sieve[i * i :: i] = False
    primes = np.nonzero(sieve)[0].astype(np.int64)
    primes_l = [int(p) for p in primes]

    def pi(x: int) -> int:
        return int(smalls[x]) if x <= v else int(larges[n // x])

    def pi_vec(x: np.ndarray) -> np.ndarray:
        out = np.empty_like(x)
        small = x <= v
        out[small] = smalls[x[small]]
        big = ~small
        if big.any():
            out[big] = larges[n // x[big]]
        return out

    total = 0

    def close_pair(rem: tuple[int, int], last_idx: int, cur: int) -> int:
        res = 0
        a, b = rem
        for e_next, e_last in {(a, b), (b, a)}:
            pmax = iroot(n // cur, e_next + e_last)
            hi = int(np.searchsorted(primes, pmax, side="right"))
            start = last_idx + 1
            if hi <= start:
                continue
            parr = primes[start:hi]
            lim = n // (cur * parr**e_next)
            if e_last == 1:
                cnts = pi_vec(lim) - smalls[parr]
            else:
                roots = np.power(lim.astype(np.float64), 1.0 / e_last)
                roots = roots.astype(np.int64)
                roots += (roots + 1) ** e_last <= lim
                roots -= roots**e_last > lim
                cnts = smalls[np.minimum(np.maximum(roots, 0), v)] - smalls[parr]
            res += int(cnts[cnts > 0].sum())
        return res

    def rec(rem: tuple[int, ...], last_idx: int, cur: int) -> None:
        nonlocal total
        if len(rem) == 1:
            e = rem[0]
            r = iroot(n // cur, e)
            last_p = primes_l[last_idx] if last_idx >= 0 else 1
            if r > last_p:
                total += pi(r) - int(smalls[last_p])
            return
        if len(rem) == 2:
            total += close_pair((rem[0], rem[1]), last_idx, cur)
            return
        for e in set(rem):
            rest = list(rem)
            rest.remove(e)
            rest_s = tuple(sorted(rest))
            j = last_idx + 1
            while j < len(primes_l):
                p = primes_l[j]
                val = cur * p**e
                if val > n:
                    break
                c = val
                jj = j + 1
                feasible = True
                for ee in sorted(rest_s, reverse=True):
                    if jj >= len(primes_l):
                        feasible = False
                        break
                    c *= primes_l[jj] ** ee
                    if c > n:
                        feasible = False
                        break
                    jj += 1
                if not feasible:
                    break
                rec(rest_s, j, val)
                j += 1

    for pat in admissible_patterns(targets):
        rec(tuple(sorted(pat)), -1, 1)
    return total


def main() -> None:
    assert count_with_b_in(100, range(2, 3)) == 51
    assert count_with_b_in(10**6, range(6, 7)) == 6189
    print(count_with_b_in(10**12, range(2, 11)))  # 672623540591


if __name__ == "__main__":
    main()
