"""Project Euler problem 599: Distinct Colourings of a Rubik's Cube.

Stickers in n colours are placed on all 24 faces of a 2x2x2 Rubik's cube;
colourings are essentially distinct if no sequence of mechanically
possible moves maps one to the other.  With n = 2 there are 183; find
the count for n = 10.

The group of sticker permutations generated by the six face turns is
G = {(sigma, t) : sigma in S_8, t in Z_3^8, sum t = 0 mod 3} of order
8! * 3^7 = 88179840: face turns realise all corner permutations (4-cycles
generate S_8), twists always sum to 0 mod 3, and whole-cube rotations are
already generated since a 2x2x2 has no fixed centres.  Burnside counts
orbits as the average of n^{cycles}.

For an element with corner permutation sigma and twists t, each
sigma-cycle of length l with twist sum tau mod 3 contributes 3 sticker
cycles when tau = 0 (three l-cycles) and 1 otherwise (a single
3l-cycle).  Summing over t first: the cycle twist sums are uniform over
{sum tau = 0 mod 3} with multiplicity 3^{8-k}, and a roots-of-unity
filter gives sum over admissible tau of the weight product as
[(n^3 + 2n)^k + 2 (n^3 - n)^k] / 3 for a permutation with k cycles.
Finally sum_{sigma in S_8} x^{k(sigma)} = x (x+1) ... (x+7), so

  count(n) = [ R((n^3 + 2n)/3) + 2 R((n^3 - n)/3) ] / 8!,

with R the 8-term rising factorial (both arguments are integers since
n^3 = n mod 3).

Verified: count(1) = 1, count(2) = 183 (given), agreement with an
explicit permutation-by-permutation Burnside sum over all of S_8, and a
direct orbit-count check of the cycle-structure argument on a two-corner
analogue group.
"""

from itertools import permutations, product
from math import factorial


def rising(x: int, m: int = 8) -> int:
    r = 1
    for i in range(m):
        r *= x + i
    return r


def colourings(n: int) -> int:
    a, b = n**3 + 2 * n, n**3 - n
    assert a % 3 == 0 and b % 3 == 0
    total, rem = divmod(rising(a // 3) + 2 * rising(b // 3), factorial(8))
    assert rem == 0
    return total


def colourings_persigma(n: int) -> int:
    """Burnside summed permutation-by-permutation over S_8."""
    tot = 0
    a, b = n**3 + 2 * n, n**3 - n
    for sig in permutations(range(8)):
        seen = [False] * 8
        k = 0
        for i in range(8):
            if not seen[i]:
                k += 1
                j = i
                while not seen[j]:
                    seen[j] = True
                    j = sig[j]
        tot += 3 ** (8 - k) * (a**k + 2 * b**k) // 3
    q, r = divmod(tot, factorial(8) * 3**7)
    assert r == 0
    return q


def two_corner_check() -> bool:
    """Direct orbit count on a 2-corner analogue vs the same formula."""
    n = 2
    total = count = 0
    for sig in permutations(range(2)):
        for t in product(range(3), repeat=2):
            if sum(t) % 3:
                continue
            count += 1
            perm = [0] * 6
            for i in range(2):
                for s in range(3):
                    perm[3 * i + s] = 3 * sig[i] + (s + t[i]) % 3
            seen = [False] * 6
            k = 0
            for i in range(6):
                if not seen[i]:
                    k += 1
                    j = i
                    while not seen[j]:
                        seen[j] = True
                        j = perm[j]
            total += n**k
    formula = (rising((n**3 + 2 * n) // 3, 2) + 2 * rising((n**3 - n) // 3, 2)) // 2
    return total // count == formula


def main() -> None:
    assert two_corner_check()
    assert colourings(1) == 1
    assert colourings(2) == 183  # given
    assert colourings_persigma(2) == 183
    assert colourings_persigma(10) == colourings(10)

    print(colourings(10))  # 12395526079546335


if __name__ == "__main__":
    main()
