"""Project Euler problem 594: Rhombus Tilings.

t(P) counts tilings of P by unit-edge rhombi and squares; O_{a,b} is the
equiangular octagon with alternating side lengths a, b.  Find t(O_{4,2}).

O_{a,b} is the zonogon generated by the four edge directions (at 0, 45,
90, 135 degrees) with multiplicities (a, b, a, b), and its tilings by
unit rhombi/squares are exactly its zonotopal tilings: every tile is the
Minkowski sum of two unit edges from distinct direction classes, so each
pair of de Bruijn pseudolines from different classes crosses exactly once
while parallel lines never cross.  Sweeping a generic direction,
a tiling becomes a sorting sequence taking the class word 1^a 2^b 3^a 4^b
to its reverse by adjacent swaps that always move a smaller class past a
larger one - and two sequences give the same tiling exactly when they
differ by commutations of swaps at positions that differ by at least two
(Elnitsky's bijection between rhombic tilings and commutation classes of
reduced words).

To count classes, count one canonical word per class: the
lexicographically least word of a class satisfies p_t >= p_{t-1} - 1 for
consecutive swap positions (otherwise the two swaps commute and swapping
them is lexicographically smaller), and conversely any violation of
lex-minimality requires bubbling a swap left past a commuting larger
position, which the staircase condition forbids.  So a memoised DP over
(current interleaving word, last swap position) counts staircase words
from the start word to the reversed word.  For (a, b) = (4, 2) there are
12! / (4! 2! 4! 2!) = 207900 interleavings, well within reach.

Verified: all three given values t(O_{1,1}) = 8, t(O_{2,1}) = 76 and
t(O_{3,2}) = 456572, plus an independent brute force for small cases that
enumerates every sorting word and groups them into commutation classes
explicitly.
"""

import sys
from functools import lru_cache

sys.setrecursionlimit(100000)


def t_octagon(a: int, b: int) -> int:
    start = (0,) * a + (1,) * b + (2,) * a + (3,) * b
    end = tuple(reversed(start))
    n = len(start)

    @lru_cache(maxsize=None)
    def f(w: tuple, p: int) -> int:
        if w == end:
            return 1
        tot = 0
        for q in range(max(0, p - 1), n - 1):
            if w[q] < w[q + 1]:
                w2 = w[:q] + (w[q + 1], w[q]) + w[q + 2 :]
                tot += f(w2, q)
        return tot

    res = f(start, 0)
    f.cache_clear()
    return res


def t_brute_classes(a: int, b: int) -> int:
    """Enumerate all sorting words, then count commutation classes."""
    start = (0,) * a + (1,) * b + (2,) * a + (3,) * b
    end = tuple(reversed(start))
    n = len(start)
    words: list[tuple] = []

    def dfs(w: tuple, seq: tuple) -> None:
        if w == end:
            words.append(seq)
            return
        for q in range(n - 1):
            if w[q] < w[q + 1]:
                dfs(w[:q] + (w[q + 1], w[q]) + w[q + 2 :], seq + (q,))

    dfs(start, ())
    canon = set()
    for seq in words:
        # bubble to the lexicographic normal form: repeatedly swap
        # adjacent commuting (gap >= 2) descents
        s = list(seq)
        changed = True
        while changed:
            changed = False
            for i in range(len(s) - 1):
                if s[i] - s[i + 1] >= 2:
                    s[i], s[i + 1] = s[i + 1], s[i]
                    changed = True
        canon.add(tuple(s))
    return len(canon)


def main() -> None:
    for ab in [(1, 1), (2, 1)]:
        assert t_octagon(*ab) == t_brute_classes(*ab), ab
    assert t_octagon(1, 1) == 8  # given
    assert t_octagon(2, 1) == 76  # given
    assert t_octagon(3, 2) == 456572  # given

    print(t_octagon(4, 2))  # 47067598


if __name__ == "__main__":
    main()
