"""Project Euler 450: Hypocycloid and Lattice Points.

Sum |x| + |y| over the integer points (with rational sin t, cos t) of all
hypocycloids with integer radii R <= 10^6, 2r < R.

Write z(t) = (R-r) e^{it} + r e^{-i(R-r)t/r}, g = gcd(R-r, r), m = (R-r)/g,
n = r/g. With u = e^{it} and w = e^{-i(R-r)t/r}, the parameter t exists
exactly when w^n = u^{-m}, and rational sin t / cos t plus integrality force
both u and w to be rational points of the unit circle. The group of rational
circle points is {+-1, +-i} times a free group generated by pi/conj(pi) over
the split Gaussian primes, so the solutions of w^n = u^{-m} are exactly
u = c^n, w = conj(c)^m over all rational circle points c (the four torsion
choices are absorbed by rotating c by i^k). Hence

    C(R, r) = { z = g (m c^n + n conj(c)^m) : c rational, z integral }.

Writing c = i^k p / conj(p) with p = s + ti primitive (gcd(s,t) = 1, s + t
odd), integrality is p^m | gn and conj(p)^n | gm, i.e. per rational prime
ell^alpha dividing N(p): v_ell(g) >= max(m alpha - v_ell(n),
n alpha - v_ell(m)). The minimal such g is G0(p, m, n), the valid g are its
multiples, and |x| + |y| scales linearly with g, giving a triangular-number
sum per class.

Part A (p = 1, G0 = 1): the four torsion points contribute, per (m, n) with
m > n >= 1 coprime, weight 4m + 2n when m + n is odd; when both are odd,
weight 4m if m = n mod 4 and 4(m + n) otherwise. Summing over coprime pairs
with s = m + n fixed reduces to totients and a Moebius sum for
sum of m over (s/2, s) coprime to s, so Part A is O(N log N).

Part B (p != 1): G0 >= h^m / n with h = N(p) >= 5 forces h <= sqrt(N/2) and
m <= 8-ish, a tiny enumeration done exactly in Gaussian-integer arithmetic.

Each geometric point has at most two (u, w) preimages (two circles meet
twice); the second is the reflection (z/conj(z)) (conj u, conj w), which lies
in the family iff z is real (partner conj(c)), or imaginary with m, n both
odd (partner -conj(c)), or diagonal with 4 | m+n (partner +-i conj(c)). Those
doubly-parametrized points are subtracted once. T(3), T(10), T(100), T(10^3)
are asserted.
"""

from math import gcd, isqrt


def tri(k):
    return k * (k + 1) // 2


def spf_sieve(n):
    spf = list(range(n + 1))
    for i in range(2, isqrt(n) + 1):
        if spf[i] == i:
            for j in range(i * i, n + 1, i):
                if spf[j] == j:
                    spf[j] = i
    return spf


def part_a(limit, spf):
    total = 0
    for s in range(3, limit + 1):
        x = s
        primes = []
        while x > 1:
            p = spf[x]
            primes.append(p)
            while x % p == 0:
                x //= p
        phi_s = s
        for p in primes:
            phi_s -= phi_s // p
        tn = tri(limit // s)
        if s % 4 == 0:
            total += 2 * s * phi_s * tn  # all pairs have m != n mod 4
            continue
        divs = [(1, 1)]
        for p in primes:
            divs += [(d * p, -mu) for d, mu in divs]
        a, b = s - 1, s // 2
        sig_up = sum(mu * d * (tri(a // d) - tri(b // d)) for d, mu in divs)
        if s % 2 == 1:
            v = 2 * sig_up + s * phi_s  # weight 4m + 2n = 2m + 2s
        else:
            v = 4 * sig_up  # s = 2 mod 4: always m = n mod 4, weight 4m
        total += v * tn
    return total


def gpow(z, e):
    r, i = 1, 0
    br, bi = z
    while e:
        if e & 1:
            r, i = r * br - i * bi, r * bi + i * br
        br, bi = br * br - bi * bi, 2 * br * bi
        e >>= 1
    return r, i


def part_b(limit, spf):
    total2 = 0  # doubled so the half-corrections stay integral
    hmax = isqrt(limit // 2) + 1
    for s in range(1, isqrt(limit) + 2):
        if s * s > hmax * hmax:
            break
        for t in range(1, isqrt(limit) + 2):
            h = s * s + t * t
            if h > hmax * hmax:
                break
            if (s + t) % 2 == 0 or gcd(s, t) != 1:
                continue
            x = h
            fac = []
            while x > 1:
                p = spf[x]
                e = 0
                while x % p == 0:
                    x //= p
                    e += 1
                fac.append((p, e))
            for m in range(2, 40):
                found_any = False
                for n in range(1, m):
                    if gcd(m, n) != 1:
                        continue
                    g0 = 1
                    ok = True
                    for ell, al in fac:
                        vn, nn = 0, n
                        while nn % ell == 0:
                            nn //= ell
                            vn += 1
                        vm, mm = 0, m
                        while mm % ell == 0:
                            mm //= ell
                            vm += 1
                        g0 *= ell ** max(0, m * al - vn, n * al - vm)
                        if (m + n) * g0 > limit:
                            ok = False
                            break
                    if not ok or (m + n) * g0 > limit:
                        continue
                    found_any = True
                    tn = tri(limit // ((m + n) * g0))
                    big_p = gpow((s, t), m + n)
                    big_pb = (big_p[0], -big_p[1])
                    dr, di = gpow((s, -t), n)
                    er, ei = gpow((s, t), m)
                    den = (dr * er - di * ei, dr * ei + di * er)
                    dn = den[0] ** 2 + den[1] ** 2
                    for k in range(4):
                        f1 = gpow((0, 1), (k * n) % 4)
                        f2 = gpow((0, 1), (-k * m) % 4)
                        numr = g0 * m * (big_p[0] * f1[0] - big_p[1] * f1[1]) + g0 * n * (
                            big_pb[0] * f2[0] - big_pb[1] * f2[1]
                        )
                        numi = g0 * m * (big_p[0] * f1[1] + big_p[1] * f1[0]) + g0 * n * (
                            big_pb[0] * f2[1] + big_pb[1] * f2[0]
                        )
                        xr = numr * den[0] + numi * den[1]
                        xi = numi * den[0] - numr * den[1]
                        assert xr % dn == 0 and xi % dn == 0
                        px, py = xr // dn, xi // dn
                        w = abs(px) + abs(py)
                        total2 += 2 * w * tn
                        if py == 0:
                            total2 -= w * tn
                        elif px == 0 and m % 2 == 1 and n % 2 == 1:
                            total2 -= w * tn
                        elif abs(px) == abs(py) and (m + n) % 4 == 0:
                            total2 -= w * tn
                if not found_any and m > 8:
                    break
    assert total2 % 2 == 0
    return total2 // 2


def total_t(limit, spf):
    return part_a(limit, spf) + part_b(limit, spf)


if __name__ == "__main__":
    spf_small = spf_sieve(1001)
    for small, expect in ((3, 10), (10, 524), (100, 580442), (1000, 583108600)):
        assert total_t(small, spf_small) == expect
    print(total_t(10**6, spf_sieve(10**6)))  # 583333163984220940
