from numba import njit


@njit(cache=True)
def _gcd(a: int, b: int) -> int:
    while b:
        a, b = b, a % b
    return a


@njit(cache=True)
def _count_not_super(d_limit: int) -> int:
    # A perfect triangle is a primitive triple with hypotenuse c = d^2, so
    # d^2 = m^2 + n^2 is itself a primitive triple generated by Euclid params
    # (p, q). The perfect triangle's area is m*n*(m^2 - n^2); count those whose
    # area is not divisible by lcm(6, 28) = 84.
    p_max = int(d_limit**0.5) + 1
    bad = 0
    for p in range(2, p_max + 1):
        for q in range(1, p):
            if p * p + q * q > d_limit:
                break
            if (p + q) & 1 and _gcd(p, q) == 1:
                m, n = (p * p - q * q) % 84, (2 * p * q) % 84
                area = (m * n) % 84
                area = (area * (((m * m - n * n) % 84 + 84) % 84)) % 84
                if area != 0:
                    bad += 1
    return bad


def solve(c_limit: int = 10**16) -> int:
    return _count_not_super(int(c_limit**0.5))


if __name__ == "__main__":
    print(solve())  # 0
