"""Project Euler 914: Triangles inside Circles.

A right triangle's minimum enclosing circle is its circumcircle, whose
diameter is the hypotenuse, so the triangle fits strictly inside a
circle of radius R iff c < 2R, i.e. c <= 2R - 1.  For a primitive
triple generated by coprime, opposite-parity m > k >= 1,

    c = m^2 + k^2,    inradius r = (a + b - c)/2 = k (m - k).

So F(R) maximises k d (d = m - k) subject to (k + d)^2 + k^2 <= 2R - 1,
d odd (which is exactly the opposite-parity condition) and
gcd(k, d) = 1.  Lagrange on the real relaxation gives d* = k* sqrt(2)
and k* = sqrt(R (2 - sqrt 2)/2), with maximum r = R (sqrt 2 - 1).
Moving k away from k* loses ~2 (k - k*)^2 while fixing parity and
coprimality costs at most a few units of d, i.e. O(k) ~ 5 * 10^8 of r,
so the integer optimum lies within |k - k*| <~ sqrt(O(k)) ~ 5 * 10^4;
the search scans a window of 2 * 10^6 for a wide safety margin (the
result is unchanged with a window of 4 * 10^6).  For each k the maximal
d is isqrt(2R - 1 - k^2) - k, and the first few valid d below it are
tried.  Verified against full brute force for R up to 10^5, including
the given F(100) = 36.
"""

from math import gcd, isqrt, sqrt


def f_max(radius: int, window: int = 2 * 10**6) -> int:
    cmax = 2 * radius - 1
    if radius <= 10**6:
        lo, hi = 1, isqrt(cmax)
    else:
        kstar = isqrt(int(radius * (2 - sqrt(2)) / 2))
        lo, hi = max(1, kstar - window), min(kstar + window, isqrt(cmax))
    best = 0
    for k in range(lo, hi + 1):
        rem = cmax - k * k
        if rem <= 0:
            break
        d = isqrt(rem) - k
        tried = 0
        while d >= 1 and tried < 6:
            if d % 2 == 1 and gcd(k, d) == 1:
                if k * d > best:
                    best = k * d
                tried += 1
            d -= 1
    return best


def f_brute(radius: int) -> int:
    cmax = 2 * radius - 1
    best = 0
    for k in range(1, isqrt(cmax) + 1):
        for m in range(k + 1, isqrt(cmax - k * k) + 1):
            if (m - k) % 2 == 1 and gcd(m, k) == 1:
                best = max(best, k * (m - k))
    return best


if __name__ == "__main__":
    assert f_brute(100) == 36
    for r in (10, 50, 100, 500, 1234, 5000, 20000):
        assert f_max(r) == f_brute(r), r
    print(f_max(10**18))  # 414213562371805310
